### ISSUE TITLE
[modify] 모바일에서 사이드바 스타일 수정, 모달창 활용, 기타 깨지는 스타일 수정

### ISSUE THREAD

**Issue by hyundonmoon** [wanted-pre-onboading-10/swit-messenger#21]
# TASK CARD

Task Description : 모바일창에서 깨지는 스타일 수정 및 모달창 활용하도록 코드 수정

Date : 2022-02-12

## to-do

- [x] 모바일 사이드바 투명하도록 수정
- [x] 연락처 필터링 input 아웃라인 수정
- [ ] 메시지 삭제, 로그아웃 시 모달 활용
- [x] 연락처 없을 시, 검색 결과 없을 시 연락처 리스트에 "없다"는 문구 표시
