### ISSUE TITLE
[modify] window.alert 와 confirm을 모달 컴포넌트로 교체, css 컨벤션에 맞춰 컴포넌트들 수정

### ISSUE THREAD

**Issue by wook95** [wanted-pre-onboading-10/swit-messenger#22]
# TASK CARD

Task Description : 컴포넌트 교체 및 컨벤션 관리

Date : [작업일]

## to-do

- [ ] 모달 스타일링 z-index 추가
- [ ] alert와 confirm을 모달로 교체
- [ ] css 컨벤션에 맞춰 코드 수정
